print('exception', file=open('exception.txt', mode='a'))